### ISSUE TITLE
Incorrect package for library classes

### ISSUE THREAD

**Issue by mbarta** [cookpad/BottomNavWatson#15]
## Current Behaviour :cry:

The package for library classes is currently `watson`.

Android studio shows the package as incorrect (but compiles), while automatic import imports the wrong one (doesn't compile).

![image](https://user-images.githubusercontent.com/2276150/89424378-9e731b80-d72f-11ea-9ee4-53776145b9ba.png)

vs.

![image](https://user-images.githubusercontent.com/2276150/89424433-ae8afb00-d72f-11ea-9d6d-709951aafb17.png)

## Expected behavior :smiley:

The package should reflect the full path: e.g. `com.cookpad.watson`, etc.

## Environment information :earth_africa:
 - OS and version: all
 - Device model: all
 - Library version: 0.0.5

**Comment by VictorAlbertos** [comment]
Done 👍
