### ISSUE TITLE
Stop initialising all navbar fragments at start

### ISSUE THREAD

**Issue by mbarta** [cookpad/BottomNavWatson#5]
## Description of the problem

Currently, the `setupWithNavController` initialisation method of BottomNavWatson class loops through enabled destinations and initialises host fragments using `obtainNavHostFragment` extension method.

Few lines later, it detaches all these initialised host fragments (along with their start destination fragments in stack) but the one selected.

This seems inefficient as at the start of the application, all the main fragments get initialised, views created and potentially HTTP calls or other code executed, just to be detached moments later.

## Proposal pf solution

The proposal of this ticket is to make the `obtainNavHostFragment` method "on-demand", potentially lazily evaluated, so that the costly initialisation of all main fragments is delayed until needed.

**Comment by VictorAlbertos** [comment]
Closed via https://github.com/cookpad/BottomNavWatson/pull/6
